sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dako22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dako22/react-test npm test -- --coverage

after_success:
  - docker build -t dako22/multi-client ./client
  - docker build -t dako22/multi-nginx ./nginx
  - docker build -t dako22/multi-server ./server
  - docker build -t dako22/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dako22/multi-client
  - docker push dako22/multi-nginx
  - docker push dako22/multi-server
  - docker push dako22/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-1"
 app: "multi-docker"
 env: "Multidocker-env"
 bucket_name: "elasticbeanstalk-ap-northeast-1-288075394530"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"
